### ISSUE TITLE
Backend changes for team event credit tracking feature 

### ISSUE THREAD

**Issue by henry-li-06** [cornell-dti/idol#150]
## Backend changes for tracking team event credits 
We want to implement team event credit tracking on IDOL to replace Google Sheets. This issue is for the required backend changes to implement this feature.  

### Required Changes
- [x] **Create a new collection in Firebase for team events** 
    - Each document (representing a team event) should have data about team event and members who have credit for the event
- [ ]   **Create new Firestore Storage folder for storing proof images**
- [ ] **Implement DAO for interacting with proof image storage folder**
    - [ ] Upload new image 
    - [ ] Get image 
    - [ ] Delete image 
- [x] **Implement DAO for interacting with team event collection** 
    - [ ] Create new team event 
    - [x] Delete team event
    - [ ] Get all team events 
    - [ ] Update team event 
- [x] **Implement the API and add the endpoints to serve the frontend** 
    - [x] *Team event CRUD APIs/endpoints 
        - [x] `/getAllTeamEvents`
        - [x] `/createTeamEvent`
        - [x] `/deleteTeamEvent`
        - [x] `/updateTeamEvent`
    - [ ] API to allow members to submit request for receiving team event credit
        - [ ] `/submitCreditRequest`

**\* Only admins/leads should have permissions to these endpoints**
