### ISSUE TITLE
Frontend changes for tracking team event credits

### ISSUE THREAD

**Issue by henry-li-06** [cornell-dti/idol#151]
## Frontend changes for tracking team event credits 
We want to implement team event credit tracking on IDOL to replace Google Sheets. This issue is for the required frontend changes to implement the basic functionality of this feature. 

### Required Changes 
- [x] Implement an API wrapper for the new backend APIs for tracking team event credits (#150)
- [ ] Add card/link on `Admin` page for tracking team event credits
    - [x] Create team event credit base page 
        - View all existing team events and be able to click into each of them
        - Create new team events (name, number of credits)
        - Delete existing team events 
    - [ ] Implement page for viewing the details of team events 
        - View list of members who attended the team event 
        - Filter/search for members 
        - Add/remove members from list of attendees 
        - Approve/reject request to receive credit for team event 
- [x] Add card/link on `Forms` base page for tracking team event credits
    - [x] Implement form to allow members to indicate that they've attended a team event 
        - [x] Search for and select team event 
        - [ ] Upload image for proof that member attended the team event
