### ISSUE TITLE
Move Edit Teams & Edit Users and allow admins to see/edit all members' profiles and headshots 

### ISSUE THREAD

**Issue by henry-li-06** [cornell-dti/idol#97]
### Todo
- [x] Move the _Edit Users_ and _Edit Teams_ pages from the _Users_ tab to the _Admin_ tab.
- [ ] Allow users with admin/lead privileges to be able to see/edit all members' profiles and headshots from the _Edit Users_ and _Edit Teams_ pages (create a link from the _Edit Users_ page to the _Edit Profile_ and _Edit Profile Image_ pages)
 
### First Steps
- [x] Some backend endpoints may need to be modified to handle provide data about any member instead of just the current user 
- [ ] Check that the backend endpoints have the correct permissions
